#!/usr/bin/bash

while :
do

	#ute
	outdoors=`wget -O - http://raspberrypi/api/number/temp/telldus/outdoors`
	echo $outdoors

	# Ällingar
	#api/number/temp/telldus/duckling
	#duckling=`wget -O - http://raspberrypi/api/number/temp/telldus/ducklings`
	#echo $duckling

	# Kycklingar
	#api/number/temp/ducklingling
	#ducklingling=`wget -O - http://raspberrypi/api/number/temp/kycklingar`
	#echo $ducklingling

	date=`date +'%%20%a%%20%H:%M'`
	echo $date

	wget -O - http://composepi/api/oled/clear
	wget -O - http://composepi/api/oled/writeline/$date
	wget -O - http://composepi/api/oled/writeline/Ute%20%20%20:$outdoors
	#wget -O - http://composepi/api/oled/writeline/Duckl%20:$duckling
	#wget -O - http://composepi/api/oled/writeline/Chickl:$ducklingling

	sleep 30
done
